services:
    app:
        image: php:8.3-fpm
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
        networks:
            - laravel_net
        command: >
            sh -c "apt-get update &&
                   apt-get install -y libpq-dev libonig-dev libzip-dev zip unzip &&
                   docker-php-ext-install pdo_mysql &&
                   php-fpm"

    webserver:
        image: nginx:latest
        volumes:
            - ./:/var/www/html
            - ./nginx:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - laravel_net

networks:
    laravel_net:
        driver: bridge
